const DW_PROJECTS_DATA = [
  {
    "title": "Gud Mishri",
    "category": "ecommerce web , seo",
    "image": "/img/projects/gudhmisrith.png",
    "alt": "Gud Mishri Custom Platform Screen Grid",
    "techs": ["Shopify Liquid", "Intent Blueprint", "Semantic Content"],
    "description": "Custom high-concurrency storefront architecture coupled with massive keyword clustering to scale a healthy sweets and traditional snacks brand on Google.",
    "roiBadge": "⚡ 0.4s Speed Lock",
    "link": "https://gudmishri.in/",
    "linkText": "Launch Site ↗",
    "isExternal": true
  },
  {
    "title": "The Marbleous",
    "category": ", seo",
    "image": "img/projects/marbess2.png",
    "alt": "SaaS Growth Metrics System Profile",
    "techs": ["Shopify Liquid", "Meta Ads Engine", "Social Media Grid","SEO Intent Blueprint"],
    "description": "Comprehensive e-commerce storefront development coupled with targeted Meta ads, performance social media marketing, and strategic SEO clustering to scale luxury marble handicrafts globally",
    "roiBadge": "📦 99.9% Cloud Uptime",
    "link": "https://www.themarbleous.com/",
    "linkText": "Launch Site ↗",
    "isExternal": true
  },
  {
    "title": "Ekatra Handmade",
    "category": "ecommerce web , seo",
    "image": "img/projects/ekatra3.png",
    "alt": "SEO Keyword Structure Platform Scale",
    "techs": ["Shopify Liquid", "Meta Ads Funnel", "Semantic SEO"],
    "description": "Custom sustainable e-commerce storefront architecture integrated with targeted Meta advertising and high-intent organic search scaling.",
    "roiBadge": "📈 +450% Traffic Growth",
    "link": "https://ekatrahandmade.com/",
    "linkText": "Launch Site ↗",
    "isExternal": true
  },
  {
    "title": "Dresszilla Rental",
    "category": "ecommerce web",
    "image": "img/projects/dresszilla.png",
    "alt": "E-Commerce Ad Optimization Funnel Matrix",
    "techs": ["Shopify Liquid", "Meta Ads Funnel", "Semantic SEO"],
    "description": "Custom designer rental storefront architecture integrated with targeted performance marketing and high-intent organic scaling for luxury fashion.",
    "roiBadge": "🚀 3.2X ROAS Multiplier",
    "link": "https://dresszilla.in/",
    "linkText": "Launch Site ↗",
    "isExternal": true
  },
  {
    "title": "Sahu Chai Wala",
    "category": "web",
    "image": "img/projects/sahuchaiwala3.png",
    "alt": "Figma UIUX Wireframing Vector Chassis",
    "techs": ["Semantic SEO", "Meta Ads Funnel", "Social Media Growth"],
    "description": "Comprehensive digital marketing architecture combining high-intent organic search scaling, targeted social media campaigns, and engagement funnels to expand a heritage tea brand's digital footprint.",
    "roiBadge": "📉 -35% Bounce Rate",
    "link": "https://sahuchaiwala.com/",
    "linkText": "Launch Site ↗",
    "isExternal": true
  },
  {
    "title": "Mum & Daughter",
    "category": "ecommerce web",
    "image": "img/projects/momd3.png",
    "alt": "Figma UIUX Wireframing Vector Chassis",
    "techs": ["Shopify Liquid", "Meta Ads Funnel", "Semantic SEO"],
    "description": "Custom mother-daughter matching wear storefront architecture integrated with targeted performance marketing and high-intent organic scaling for ethnic lifestyle fashion.",
    "roiBadge": "📉 -35% Bounce Rate",
    "link": "https://mumdaughter.com/",
    "linkText": "Launch Site ↗",
    "isExternal": true
  },
  {
    "title": "Raja & Raya",
    "category": "web ecommerce",
    "image": "img/projects/rajaraya3.png",
    "alt": "Node Code Repository Automation Framework",
    "techs": ["Shopify Liquid", "Meta Ads Funnel", "Semantic SEO"],
    "description": "Custom family twinning apparel storefront optimized for performance marketing and organic growth.",
    "roiBadge": "⚡ Instant Stock Sync",
    "link": "https://rajaandraya.com/",
    "linkText": "Launch Site ↗",
    "isExternal": true
  },
  {
    "title": "Home Arte India",
    "category": "web ecommerce",
    "image": "img/projects/homeart3.png",
    "alt": "Node Code Repository Automation Framework",
    "techs": ["Shopify Liquid", "Meta Ads Funnel", "Semantic SEO"],
    "description": "Custom home decor storefront optimized for performance marketing and organic growth.",
    "roiBadge": "⚡ Instant Stock Sync",
    "link": "https://www.homearteindia.com/",
    "linkText": "Launch Site ↗",
    "isExternal": true
  },
  {
    "title": "Reducetax",
    "category": "web ",
    "image": "img/projects/reducetaxth.png",
    "alt": "Node Code Repository Automation Framework",
    "techs": ["Shopify Liquid", "Meta Ads Funnel", "Semantic SEO"],
    "description": "Custom home decor storefront optimized for performance marketing and organic growth.",
    "roiBadge": "⚡ Instant Stock Sync",
    "link": "https://reducetax.in/",
    "linkText": "Launch Site ↗",
    "isExternal": true
  }
];